### ISSUE TITLE
Production ready ?

### ISSUE THREAD

**Issue by Toilal** [rvs-fluid-it/dw-jar-to-war#1]
Hi,

I'm a dropwizard fan, thank you for this project :).

What is the state of the project ? Is it production ready ?

**Comment by rvs-fluid-it** [comment]
Hi Toilal,

I'm glad you like the project.

'Wizard in a box' will be production ready or not depending on your specific case. If your Dropwizard application (and its bundles) do the typical actions with the jetty server object like defining servlets, filters, attributes, I think that 'Wizard in a box' is production ready. If the bundles are relying on Jetty specific features then some extra work will be needed in 'Wizard in a box'. But even in this case it will be less work then making a barebones Jersey application ready for production on a JEE application server.

Currently our team is developing an Angular + Dropwizard application and I intend to go into production on a Weblogic 12c container within two months. The application is already running on a test environment.

In my case a bit of time was spent on tweaking the classloader hierarchy of the Weblogic container (yes indeed the typical JEE fun part ...). Depending on your chosen production application server this will take less or more time. 

Regards
