### ISSUE TITLE
Finding where assets are deployed

### ISSUE THREAD

**Issue by Catchwa** [rvs-fluid-it/dw-jar-to-war#18]
I'm using 0.8-2-1 against WildFly (aka JBoss) 8.1

My Dropwizard REST calls work fine, but I'm having trouble finding where my assets are getting served to. This works fine in the Jetty standalone-jar version of my project, where I have all Dropwizard resources served from /api/\* and assets are served from /\*  (i.e. so that I can browse to http://localhost:8082 and my assets/index.htm is served up)

In the Wildfly logs I see the following (note: my war is called reporting.war):
[wildfly-logs.txt](https://github.com/rvs-fluid-it/wizard-in-a-box/files/46805/wildfly-logs.txt)

I register the assets like this in my JAR app:

```
@Override
public void initialize(Bootstrap<ArgusConfiguration> bootstrap)
{
    bootstrap.addBundle(new AssetsBundle("/assets", "/"));
}
```

...and then my YAML file when running in standalone JAR mode looks like:

server:
  type: simple
  rootPath: /api/*
  applicationContextPath: /
  adminContextPath: /admin

So, now in my wizard-in-a-box WAR module, I have YAML as follows:

server:
  type: bridge
  applicationContextPath: /api
  adminContextPath: /admin
  servletsMappedFromRootContext:
    - assets

So currently, I can send requests to the services at https://localhost:8443/reporting/api/<blah> but when I go to https://localhost:8443/reporting I get a 404, when I'd expect the assets/index.htm to be served up.

What am I doing wrong? Based on my reading of the logs, "Servlet mapping [assets->[/*]] detected" should mean that they're getting deployed to the root of the "reporting" path.

**Comment by Catchwa** [comment]
...and in the maven-war-plugin section of the reporting-war pom.xml, I'm copying two sets of resources into my WAR (my projects are called reporting-jar and reporting-war).

```
                <webResources>
                    <resource>
                        <!-- this is relative to the pom.xml directory -->
                        <directory>${project.basedir}/src/main/resources</directory>
                    </resource>
                    <resource>
                        <!-- this is relative to the pom.xml directory -->
                        <directory>${project.basedir}/../reporting-jar/src/main/resources</directory>
                    </resource>
                </webResources>
```

**Comment by rvs-fluid-it** [comment]
What I have as a typical configuration is:

``` yaml
server:
  type: bridge
  applicationContextPath: /dynamic
  adminContextPath: /admin
  servletsMappedFromRootContext:
    - assets

assets:
  mappings:
    /assets: /static

...
```

And then the following URLs will be exposed:  

protocol://host:port/context/dynamic/... for the REST-endpoints
protocol://host:port/context/admin/... for the admin interface
protocol://host:port/context/static/... for the static resources wich will be served from the assets package ( -> classpath resources)

For the assets configuration part see http://www.dropwizard.io/0.9.1/docs/manual/core.html#serving-assets

I hope it helps

**Comment by Catchwa** [comment]
I've gotten it working, but perhaps not in the most optimal way (there's a double-distribution of assets, for starters). I'll add it here just in case it helps others.

In my WAR project POM, I have:

```
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-war-plugin</artifactId>
            <version>2.6</version>
            <configuration>
                <failOnMissingWebXml>false</failOnMissingWebXml>
                <webResources>
                    <resource>
                        <directory>${project.basedir}/src/main/resources</directory>
                        <!-- YAML configuration file is on the classpath, but should not be served as a web resource -->
                        <excludes>
                            <exclude>**/*.yml</exclude>
                            <exclude>**/*.yaml</exclude>
                        </excludes>
                    </resource>
                    <resource>
                        <!-- Serve reporting JAR assets from the root of the WAR -->
                        <directory>${project.basedir}/../reporting-jar/src/main/resources/assets</directory>
                    </resource>
                </webResources>
            </configuration>
        </plugin>
```

The YAML file of my WAR project has:

```
server:
  type: bridge
  applicationContextPath: /api
  adminContextPath: /admin
```

(i.e. I don't use servletsMappedFromRootContext as they're directly copied into the root of the WAR)

In the ReportingApplication class file in my JAR project, I have:

```
@Override
public void initialize(Bootstrap<ReportingConfiguration> bootstrap)
{
    // Only add an assets bundle if the class isn't being called from the ReportingWarApplication class
    if (bootstrap.getApplication() instanceof ReportingApplication)
    {
        bootstrap.addBundle(new AssetsBundle("/assets", "/"));
    }
}
```
