### ISSUE TITLE
ReflectionConfigurationWriter and properties using Jackson annotations

### ISSUE THREAD

**Issue by lehcim** [rvs-fluid-it/dw-jar-to-war#19]
ReflectionConfigurationWriter works well for pure JavaBean configurations classes, however it fails if Jackson annotations Json{Property,Setter,Getter} are used on configuration properties. To be more precise: in the context.xml file, you'll need to override the real JavaBean name, not the external Yaml name defined using annotations.

Let's take an example:

``` java
class Config {
    @JsonProperty("login")
    private String userName ;
    public String getUserName() { return userName ; }
    public void setUserName(String userName) { this.userName = userName ; }
}
```

In the application.yaml file, we use the syntax:

``` yaml
login: lehcim
```

then it's natural to override the property using the same name "login" in a context.xml file, like this :

``` xml
<Environment name="dropwizard/configuration/login" value="lehcim" type="java.lang.String" />
```

but at runtime it throws an exception :

```
ERROR [2016-01-04 14:01:01,064] be.fluid_it.tools.dropwizard.box.config.JndiConfigurationBridge: Can't write property uri to Dropwizard Configuration
! java.lang.NoSuchMethodException: sample.server.Configuration.getUserName()
! at java.lang.Class.getMethod(Class.java:1670) ~[na:1.7.0_71]
! at be.fluid_it.tools.dropwizard.box.config.ReflectionConfigurationWriter.write(ReflectionConfigurationWriter.java:57) ~[wizard-in-a-box-0.8-2-1.jar:na]
! ... 23 common frames omitted
```

Of course, the syntax that currently works is :

``` xml
<Environment name="dropwizard/configuration/userName" value="lehcim" type="java.lang.String" />
```

but it's not coherent with the yaml config file, and it requires that the administrator who edits the context.xml file knows the real name of the property "userName", by reading the source code or a to be written documentation...

I see two solution for this issue:
- Rename all the problematic properties in my application server code (boring)
- Use Jackson introspection in ReflectionConfigurationWriter (fun)

A pull request implementing the second solution will follow.

**Comment by lehcim** [comment]
Here is the pull request: https://github.com/rvs-fluid-it/wizard-in-a-box/pull/20

**Comment by lehcim** [comment]
Thanks for the pull. I think this issue could be closed now.

BTW, you can also merge it to the dropwizard-0.9.x branch, the original code is identical.

**Comment by rvs-fluid-it** [comment]
A new version 0.8.2-2 has been released into Maven central.
