### ISSUE TITLE
Assets Module

### ISSUE THREAD

**Issue by alexan** [rvs-fluid-it/dw-jar-to-war#2]
Hi,
I've tried your module and got most of my application working. Thanks for your effort.

I've tried to get the asset module working. But got no luck. During debugging I figured out, that the HttpServletRequest.getServletPath resolves to two different locations in the io.dropwizard.servlets.assets.AssetServlet:
- simple server bound to /application HttpServletRequest.getServletPath is "/"
- bridge server bound to /applictaion HttpServletRequest.getServletPath is "/applictaion"

for the moment I have three workaround options:
- copy the assets to the war project webapp directory. This has the Problem that the assets are on two different locations in war and jar mode. war: root jar: /application
- use a separate project for assets
- only use war for development

**Comment by rvs-fluid-it** [comment]
Hi Alex,

Assets are not yet supported.
It's indeed an important missing feature, so I'll add the issue to the planning of the next release (version 0.8-1-2, expected release date +/- 30/4/2015).

**Comment by alexan** [comment]
Hi,
thanks for your fast feedback, your work is appreciated.

**Comment by rvs-fluid-it** [comment]
Hi Alex,

This week I've been busy with security (See https://github.com/rvs-fluid-it/shiro-jee-authc)
Assets is added to the sprint starting next week.

**Comment by alexan** [comment]
did you do any progress in your sprint. 
Is there a way I can support your work?

**Comment by rvs-fluid-it** [comment]
Hi,

Support for assets is added to version 0.8-1-2.
I welcome contributions, so feel free to send pull requests.
