### ISSUE TITLE
Gradle support?

### ISSUE THREAD

**Issue by molszewski** [rvs-fluid-it/dw-jar-to-war#6]
Hi!
We're trying to build a war containing dropwizard app and your library looks very promising. The only issue is that we use Gradle instead of Maven to build our application and it is not clear to us how to map Maven modules into Gradle projects. 

Can you share some insight on this if possible?

Thanks!

**Comment by rvs-fluid-it** [comment]
Hi,

Wizard in a box is just a jar which you can grab from Maven central.
It means that you can use for your application any build tool that can fetch dependencies from Maven repositories.

To declare a depency you need to do in Gradle something similar as:
compile 'be.fluid-it.tools.dropwizard:wizard-in-a-box:0.8-1-2'

It is a good practice to split your project into modules. In Gradle they name it then a mutli project build.
See http://www.petrikainulainen.net/programming/gradle/getting-started-with-gradle-creating-a-multi-project-build/

I hope it will get you on the right track.

Regards,

(Disclaimer: I'm not a Gradle expert)

**Comment by molszewski** [comment]
Hello again

Thanks for your help - it confirmed the direction we should take and put us on the right track. We managed to get it working!

For anyone interested we ended up with a following working solution:
1. Create "parent" gradle project and "sample-app" subproject.
2. Parent project should contain only "YourWebApplication" class extending wizard-in-a-box WebApplication and annotated with javax WebListener
3. Parent build.gradle should be similar to:
   
   ```
   allprojects {
       apply plugin: 'java'
   
       project.sourceCompatibility = '1.7'
       project.targetCompatibility = '1.7'
   
       repositories{
           mavenCentral()
       }
   }
   
   apply plugin: 'war'
   
   dependencies {
       compile 'be.fluid-it.tools.dropwizard:wizard-in-a-box:0.8-1-2'
       compile project (':sample-app')
   }
   
   war {} // yes it is empty indeed!
   ```

Hope this helps!
