### ISSUE TITLE
Maven Shitty Plugin

### ISSUE THREAD

**Issue by Toilal** [rvs-fluid-it/dw-jar-to-war#9]
Any alternative for this plugin ? It seems unmaintained since 2008 ...

**Comment by rvs-fluid-it** [comment]
I believe the maven-invoker-plugin (https://maven.apache.org/plugins/maven-invoker-plugin/) is often used for this kind of integration tests.
But on the other hand the maven shitty plugin does it work pretty well, so I don't feel an urgent need to replace it.
But if you want to swap it with something better, feel free to send a pull request.

**Comment by Toilal** [comment]
I'll try to make a pull request with invoker plugin thanks.

Base issue is that build fails on our Jenkins CI, because maven invocation inside shitty plugin doesn't load maven settings from Jenkins. Hope it will behave better with invoker plugin.

**Comment by rvs-fluid-it** [comment]
I'll keep my fingers crossed
